### ISSUE TITLE
pinentry-touchid cannot be configured until after you have a key

### ISSUE THREAD

**Issue by VxJasonxV** [jorgelbg/pinentry-touchid#12]
I set up pinentry-touchid at the start of a new machine before creating a new GPG key, I was never asked for a passphrase when going through key generation and was left very confused. Only after disabling the configuration (commenting out the gpg-agent.conf configuration line) was I prompted for a GPG key passphrase.

I'm not informed enough on the particulars of GPG to offer a documentation change, but I am left feeling like it should be made clear that pinentry-touchid should only be configured *after* creating a new / importing an existing key, and that the key must have a passphrase, hence the whole purpose of pinentry.

**Comment by jorgelbg** [comment]
Good catch @VxJasonxV! 

I had never tried creating a brand new GPG key while having pinentry-touchid configured in the `gpg-agent.conf` 😅. I will try to implement a fallback to pinentry-mac for this case, or update the documentation accordingly.

**Comment by jorgelbg** [comment]
@VxJasonxV This should work now, if you are willing to build from the main branch, othwerwise I'm planning on tagging a new release in the next few days.
