### ISSUE TITLE
Conflict log file owner when using fast user switching on the Macbook.

### ISSUE THREAD

**Issue by fioleto** [jorgelbg/pinentry-touchid#13]
Hello.

I face a problem that conflicting log file owners when using fast user switching.
Therefore, every time I switch users, required to remove `/tmp/pinentry-touchid.log` as a root.

Could you possibly add some prefix or suffix to the default log file name,  enable a specific log file path, or just the option of omitting logfile?

Thank you.

**Comment by jorgelbg** [comment]
@fioleto Thanks for the report. This was indeed an issue. A fix was added in commit https://github.com/jorgelbg/pinentry-touchid/commit/3ebb30fcabe3916fe0dc776ac0b555d8983545f3 which now uses a user-scoped directory. I will do a release containing the fix shortly.
