### ISSUE TITLE
pinentry-touchid -fix is not a command

### ISSUE THREAD

**Issue by ThisIsMissEm** [jorgelbg/pinentry-touchid#27]
## Describe the bug

I just installed pinentry-touchid from homebrew, and I'm following the readme, and when I run:

```
$ pinentry-touchid -fix
```

I get the message:

```
flag provided but not defined: -fix
Usage of pinentry-touchid:
  -check
    	Verify that pinentry-mac is present in the system
```

`pinentry-touchid -check` works fine though.

## System information

**macOS**
 - Architecture: Intel
 - Version: 12.3.1

**GPG**
 - Output of `gpg --version`
```
gpg (GnuPG) 2.3.6
libgcrypt 1.10.1
```

 - Installed via Homebrew? yes

**Configuration**

 - Please attach the output of the command `gpgconf`.

```
gpg:OpenPGP:/usr/local/Cellar/gnupg/2.3.6/bin/gpg
gpgsm:S/MIME:/usr/local/Cellar/gnupg/2.3.6/bin/gpgsm
keyboxd:Public Keys:/usr/local/Cellar/gnupg/2.3.6/libexec/keyboxd
gpg-agent:Private Keys:/usr/local/Cellar/gnupg/2.3.6/bin/gpg-agent
scdaemon:Smartcards:/usr/local/Cellar/gnupg/2.3.6/libexec/scdaemon
dirmngr:Network:/usr/local/Cellar/gnupg/2.3.6/bin/dirmngr
pinentry:Passphrase Entry:/usr/local/opt/pinentry/bin/pinentry
```

I couldn't actually get gpgconf to interact at all with my `~/.gnupg/gpg-agent.conf` file, changes there just weren't respected, and `gpgconf` always output the same, even after restarting:

As such the rest of the questions here aren't particularly answerable. The issue from `pinentry-touchid -fix` does seem directly that it's just missing that CLI flag.

--- 

**Logs**

**`gpg-agent`:**

It would be very useful for us if you could enable the `basic` debug info for your `gpg-agent` and attach the generated log. Add the following to your `~/.gpg-agent.conf`:

```
debug-level basic
log-file /Users/<USERNAME>/.gnupg/gpg-agent.log
```

Reload `gpg-agent` with the following command:
```sh
$ gpg-connect-agent reloadagent /bye
```

Add/attach the relevant section of the log to this issue (feel free to redact your key IDs).

**`pinentry-touchid`:**

`pinentry-touchid` also generates its own log which you can find in `$TMPDIR/pinentry-touchid.log`.

**Comment by artyorsh** [comment]
Had the same when installing with Homebrew and got it fixed [installing manually](https://github.com/jorgelbg/pinentry-touchid#manual-installation)

**Comment by ThisIsMissEm** [comment]
Turns out it's an issue because those are installing 0.0.2, the stable release, not the release candidate for 0.0.3

**Comment by artyorsh** [comment]
@jorgelbg can we update?

**Comment by benwaffle** [comment]
@jorgelbg can you tag a v0.0.3 release?
